# Introduction 

## Problem Statement
Many cities are dependent on the private car. Car-dependency is unsustainable, however, and car-centric societies must use alternate transport modes to grow into sustainable urban centers. Novel modes, such as micromobility, ridehailing, ridesharing, and autonomous vehicles solve the sustainability problem present in car-centric societies. Novel modes exhaust less vehicular emissions, decrease roadway congestion, increase health, increase public transit usage, and are economically viable. As urban centers attempt to shift from a car-centric environment to a multi-modal system, forecasters are challenged with modeling accurate novel mode ridership and level of service. Estimating the updake of novel mode usage, and understanding the service capabilities of those novel modes, is critical to  a sustainable future.

Unfortunately, forecasting the ridership, level of service, and utilization of novel modes is a challenging feat. The ridership of bike share, an affordable and sustainable bike rent program, has been modeled many times each with a different methodology (e.g., @hyland18, @biehl19, @cho22, @li18, @welch20, @zhou19, @song19). Similarly, forecasters struggle to find the best technique for estimating the ridership and hub location of e-scooters (public electric scooters) and in what locations they would be most effective (e.g, @zuniga22, @tuli21, @zhang21, @lee21, @leeb21, @hosseinzadeh21). In general, forecasters have modeled micromobility (bike share, e-scooters, e-bikes) in many ways, yet few have attempted to model multiple novel modes simultaneously (e.g., @reck21, @campbell16, @lazarus20, @mckenzie19, @younes20). Ride hail and ride share, which allow users to hire a driver, behave differently than regular car modes. Given their unique nature, understanding their behavior and service capabilities is particularly challenging (e.g., @kang21, @li20, @dong20, @dean21). 










The usage of bike share, an affordable and sustainable bike rent program, has been modeled countless times each with a different methodology (e.g., @hyland18, @biehl19, @cho22, @li18, @welch20, @zhou19, @song19). Forecasters are riddled with determining the best technique for understanding who uses e-scooters (public electric scooters) and in what locations they would be most effective (e.g, @zuniga22, @tuli21, @zhang21, @lee21, @leeb21, @hosseinzadeh21). In general, forecasters have modeled micromobility (bike share, e-scooters, e-bikes) in many ways, yet few have attempted to model multiple novel modes simultaneously (e.g., @reck21, @campbell16, @lazarus20, @mckenzie19, @younes20). Ride hail and ride share, which allow users to hire a driver, behave differently than regular car modes. Given their unique nature, understanding their behavior and service capabilities is particularly challenging (e.g., @kang21, @li20, @dong20, @dean21). Forecasters have even attempted to understand the effects of autonomous vehicles, even though to date little to no data exists on fully-autonomous vehicles (e.g., @mo22, @wadud21, @zhou20). New transport technologies are becoming more prominent each day, and equally so is the need to accurately capture their behavior. 

Various efforts have been made to model novel transport modes accurately, but since methodologies are dissimilar with one another it remains difficult to determine the best approach. For example, some forecasters have chosen to model novel transport modes with an activity-based model, which uses daily activity patterns as the central tool to model an individual’s travel behavior (e.g., @xu19, @muhammad19, @macfarlane21). Other forecasters use multi-agent simulation, which focuses on modeling the interactions between different agents, to understand new transport technologies (e.g., @shimizu13, @sanchez19, @horl19b). In general, many forecasters have modeled novel modes in activity-based models, multi-agent simulations, or other modeling frameworks by using a logit based regression analysis, which uses a function to understand characteristics of the modes (e.g., @welch20, @lee21, @dong20). Some chose a simpler approach, spatial analysis and geography data, to understand new transport technologies (e.g., @hyland18, @cho22, @hosseinzadeh21). Forecasters have even attempted to use machine learning to better understand novel modes! (e.g., @zhou19). With limited data on novel transport modes, the validity of the results from each approach can be difficult to verify. 
 
## Purpose of Research 
In this paper we examine novel mode forecasts generated by different activity-based model and multi-agent simulation mode choice combinations. By examining the ride hail service capabilities between each combination, we hope to understand which mode choice combination is best, or if a best combination even exists. Since only limited data on novel mode usage exists, it seems logical to test different mode choice combinations to determine the best way to model new transport technologies. Overall, this paper aims to give forecasters additional direction in how to model novel transport modes.






