# Literature Review

Things to keep in mind

Why not just jump straight into the definition of ABM vs micro simulation? Is it possible to use MATsim without an ABM? Or how do people normally get travel times if they don't hook up to beam?

Well, think about why we need two tools. Why not just use activitysim?

You aren't writing a textbook. You are laying the groundwork for helping people understand why you are doing the methodology you are doing.

Outline

2.1 Activity-based Models vs. Microsimulation Tools
- describe what they are and how they differ
- define examples (ActivitySim, MATSim, BEAM)

2.2 Link between ABMs and Microsimulation Tools
- describe if abm can run without microsimulation, or if we need microsimulation to get travel times
- describe if microsimulation can run without first running an abm
- describe the advantages of using an abm to generate the inputs to microsimulation

2.3 Mode Choice in ABMs vs. Mode Choice in Microsimulation Tools
- describe that mode choice in activity-based models can often be advanced
- briefly describe some structures that have been used to model mode choice in abms
- describe that mode choice in microsimulation tools can often be simple
- briefly describe the mode choice in MatSim as an example
- DONT describe AsIM or BEAM model -- that is first step in methodology 

2.4 Linking Mode Choice between ABMs and Microsimulation Tools
- describe why we might need mode choice in each one, and why turning off mode choice in one isn't always the correct option (adv. of ride hail in beam)
- describe that if the two models are often used simultaneously, why would their mode choice be different
- describe attempt by Horl to improve mode choice in BEAM and how what we are doing is similar

## Activity-based Models vs. Microsimulation Tools












