# Discussion {#discussion}
According to the results presented in Section \@ref(results), mode choice structure significantly affects novel mode ridership and service capabilities. The results also suggest that whether or not ride hail exists in the multi-agent simulation's input plans does not make a significant difference to overall ride hail statistics. With both of these determinations in mind, we conclude that forecasters should use *both* an activity-based model and a multi-agent simulation to forecast novel mode usage. However, we suggest that only one of these tools should be used to forecast ridership, while the multi-agent simulation should be used to forecast service capabilities. The results, backed up by the literature review conducted in Section \@ref(lit), illustrate why the multi-agent simulation should be used for service capability estimation. The results also suggest why only one of the tools should be used for ridership estimation. Specifically, the extreme variation in ridership among the 10 scenarios supports this conclusion. Overall, with these conclusions in mind, we offer two methodological approaches that forecasters should use to model novel modes:

  1. Frozen Multi-Agent Estimation
  2. Adjusted/Enhanced Multi-Agent Estimation

## Frozen Multi-Agent Estimation
In the Frozen Multi-Agent Estimation technique, we advice forecasters to use an activity-based model to estimate novel mode ridership usage. The activity-based model would be in charge of forecasting which users are prone to using the new mode and how many of these users should exist. Then, we advice forecasters to input these final plans into a multi-agent simulation to simulate all the trips. Mode choice innovation would be turned off (frozen) within the multi-agent simulation, meaning all mode choice would have been conducted in the activity-based model. The multi-agent simulation, however, would be used to verify that all the estimated novel mode trips are possible. In addition, the multi-agent simulation would use a simulated fleet of vehicles, variable wait times if applicable, and a street network to provide realistic service capability estimation. 

The Frozen Multi-Agent Estimation technique is identical to the AsimRideHail scenario presented in Section \@ref(results). The results from the AsimRideHail scenario were reasonable, understandable, and realistic. For example, ridership values for this scenario were closest to the expected regional totals. Wait time values were also reasonable, especially when accounting for the amount of total users in comparison to the size of the ride hail fleet. In addition, the AsimRideHail scenario avoided all the pitfalls that existed in the scenarios where BEAM modal innovation was turned on. For example, without modal innovation turned on in BEAM, the vehicle allocation problem was avoided; car users did not unexpectably switch to a ride hailing mode. This approach was simplest, because a consistent mode choice structure wasn't needed, but the advantages of the multi-agent simulation tool were exploited.

Overall, the Frozen Multi-Agent Estimation technique will allow forecasters to exploit the advantages of using an activity-based model and of using a multi-agent simulation while also avoiding the disadvantages of each tool. Our results back this statement, as this methodology will produce ridership closest to the regional totals, while also producing realistic expected wait times and other service capabilities. We recommend that forecasters use this methodology for simple, yet effective ride hail estimation. Alternatively, we also recommend the Adjusted/Enhanced Multi-Agent Estimation technique if desired.

## Adjusted/Enhanced Multi-Agent Estimation
In the Adjusted/Enhanced Multi-Agent Estimation technique, we advice forecasters to use a hybrid between an activity-based model and a multi-agent simulation. The activity-based model would be used to generate the input plans, which would exclude ride hail modes. The multi-agent simulation would be used to update those choices provided by the input plans to include ride hail modes. In other words, the multi-agent simulation would be the primary tool for forecasting ride hail trips. Within the multi-agent simulation, however, we recommend adjusting the internal structure as to avoid its inherit pitfalls. By adjusting the internal code of the multi-agent simulation, many of its disadvantages are overcome. For example, one may consider changing its trip-based mode choice structure to align closer with an activity-based model (i.e. use tour mode choice variables). 

The Adjusted/Enhanced Multi-Agent Estimation technique was similar to the BeamRideHailType scenarios in our study. These scenarios, which used the *RideHail* mode choice model, were built to overcome the inherit weaknesses of the multi-agent simulation present in the *All* mode choice model. Specifically, we faced an imperfect car-matching algorithm paired with a trip-based mode choice model. These weaknesses caused an inexplicably high number of car users to choose ride hail alternatives, even if this choice didn't make logical sense. Therefore, we avoided these pitfalls by only allowing those most likely to choose ride hail alternatives (non-car users) to be able to choose ride hail alternatives. Unfortunately, we were unable to perfect our hybrid model because the ride hail choice was provided excessively to all non-car users. However, by limiting ride hail to only those who would go through the clear modes step, the *RideHail* model would have performed exceptionally well at forecasting novel modes. 

Overall, the Adjusted/Enhanced Multi-Agent Estimation technique will allow forecasters to perform all ride hail estimation within a multi-agent simulation. The forecasters will be able to fully exploit the benefits that exist when using multi-agent simulation, while being sure that their results are valid. Our results show that if the inherit weaknesses present in the multi-agent simulation can be overcome, ride hail ridership, utilization, and service capabilities will be estimated effectively. We warn however, that the Adjusted/Enhanced Multi-Agent Estimation technique will be time consuming and difficult to implement. It requires forecasters to fully understand how the multi-agent simulation they choose to use functions. 
  
## Additional Findings  
Along with recommending two methodological approaches to forecasting novel modes, we provide a few additional suggestions. First, we recommend using all path, person, and location type variables to model the mode choice utility. A wide variety of utility parameters helps to create a more realistic modeling environment. In addition, we advice forecasters to tread carefully when forecasting novel modes with activity-based models or multi-agent simulations. Both tools are flexible enough to allow the user to change how they fundamentally work; they can even be changed until the users gets the desired outcome. Using both tools will minimize this risk. Forecaster should  also be aware of model consistency and the mode choice structures being used. Overall, by following the recommendations given in this section, along with professional judgement, modeling novel modes between activity-based models and multi-agent simulations becomes effective. 

 
  
