# Conclusion {#conclusion}
The increasing usage of on-demand transport modes such as ride-hailing and microtransit has challenged forecasters with finding the best methodology to capturing behavior related to these new modes. Spatial analysis, activity-based models, and multi-agent simulation are common methodological approaches, but some professional disagreement exists as to which approach is best for forecasting the availability and service capabilities of on-demand services. Additional question surrounds how successful a paired activity-based model and multi-agent simulation would fare in practice. By using the daily activity plans generated by ActivitySim, an activity-based model, as inputs to BEAM, a multi-agent simulation tool, we constructed nine different model combinations where the choice of ride-hailing varied between ActivitySim and BEAM. We also adjusted the mode choice utility equation between each model combination. By analyzing the ride-hailing ridership and level of service between each methodological combination, we found that pairing an activity-based model and multi-agent simulation is a promising approach to forecasting the performance of ride-hailing services. However, in our research the multi-agent simulation had a tendency to overestimate ride-hailing ridership, while estimating realistic level of service forecasts. As a result, we believe there is an opportunity in future research to implement a feedback loop between an activity-based model and multi-agent simulation to create realistic and useful ride-hailing level of service and usage estimates.

Overall, accurately predicting the behavior and service capabilities of on-demand services is the key to a sustainable future. Ride-hailing and other novel modes are central to clean air, organized cities, and the effective movement of people. By accurately predicting the usage of ride-hailing and microtransit vehicles, we can help improve our cities and our lives. Overall, we can directly change the course of our future by how we estimate ride-hailing and other travel behavior, and so, should we not estimate it with the best approaches available? This research along with future research will help in these efforts to accurately predict the ever changing behavior and capabilities of transportation itself.  

\nocite{*}


