# Limitations
Various components of the activity-based model and multi-agent simulation were not perfected. First, the ActivitySim model for the Salt Lake City, Utah region was based mainly off of the MTC example model from ActivitySim's archives. As a result, much of the parameters were held constant in our case study. The trip and tour mode choice coefficients were however, calibrated to the case study region. Since the other parameters were held constant, like the activity estimation parameters, the mode choice coefficients could only be calibrated so far. The mode choices determined by ActivitySim were close to regional target values, but were not perfect. A similar limitation existed within BEAM, where the mode choice coefficients were only calibrated as far as reasonably possible. The mode choices produced by BEAM were slightly different than the target values, and did not represent a completely accurate total modal distribution. Time restraint on the project prevented us from improving the accuracy of the utility parameters used to calculate mode choice in ActivitySim and BEAM. Fortunately, the results in our research remain valid since the mode choice combinations comparisons were more significant than their exact predictions.

In addition to the mode choice parameters, a few more limitations existed with the BEAM software. BEAM was in development throughout the life of this research, so its capabilities were also in development. For example, activity plans remained constant across each iteration. BEAM is exclusively a trip-based model; no tour level decision making occured. In addition, the BEAM developers let us know that the plans files used to create Figure \@ref(fig:sankey) were not a perfect representation of the mode choices chosen each iteration. These plans files did however give a sufficiently good idea of what was happening behind the scenes. The mode choice models we developed within BEAM also included a few limitations. The *All* structure had various car-matching difficulties as well as path-building difficulties. The *RideHail* structure gave the ride hail alternative to all individuals instead of only those who had their mode wipped between iterations.

The two biggest limitations with the input files related to the driver fleet and the network file. The driver fleet was developed by a fellow research student from another university, and the student did not factor in university and school location when statistically modeling the start location of each ride hail vehicle. Second, the network file we used only included main roadways, because it was too difficult to develop a reliable all streets network from the resources available. The last significant limitation of the research was that the results were from the 12th iteration of a 15% scenario size. Due to our limited resources with computing power, larger scenarios and more iterations was too computationally heavy for our computers. 

## Further Research
With these limitations in mind, a few ideas are relevant for future research studies. First, we first recommend updating BEAM's mode choice model to include tour level choices, an improved car matching algorithm, and an improved *RideHail* model. By conducting these few changes, accurate hybrid models between ActivitySim and BEAM could be developed, further supporting the results of this research. In addition to fixing these specific models, we recommend in future research to develop a hybrid activity-based model and multi-agent simulation with the MATSim software. MATSim is a more stable and reliable multi-agent simulation than BEAM, and connecting MATSim with an activity-based model to forecast novel modes could prove powerful. Finally, the last recommendation for further research is abstract in that we believe combining an activity-based model and a multi-agent simulation into one model could prove highly useful. Creating a model which incorporates activity-based components into a multi-agent simulation tool may be the best methodological approach to forecasting new transport technologies to date. 

  
