# Conclusions

The advent of novel transport modes has challenged forecasters with finding the best methodology to capturing behavior and estimating service capabilities. Micromobility, ride hail and ride share, and even autonomous vehicles have been forecasted with an array of different approaches like activity-based models, spatial analysis, and even machine learning. These methodologies are dissimilar and their different results are difficult to access. Interestingly, linking two disparate approaches to model novel modes has only been attempted in a few research studies. None of these studies however, have attempted to model new transport technologies generated by a paired activity-based model and multi-agent simulation. In this research, we examined novel mode forecasts generated by different activity-based model and multi-agent simulation mode choice combinations. Using ActivitySim as the activity-based model and BEAM as the multi-agent simulation, we conducted 10 different mode choice experiments. By adjusting the mode choice alternatives in ActivitySim, adjusting the mode choice model within BEAM, and adjusting the mode choice utility coefficients, we found the two most optimal paths to modeling novel modes between an activity-based model and a multi-agent simulation.

We determined that the Frozen Multi-Agent Estimation and the Adjusted/Enhanced Multi-Agent Estimation techniques were the most effective at modeling novel modes with a linked activity-based model and multi-agent simulation. The Frozen Multi-Agent Estimation technique suggests only estimating novel mode usage in the activity-based model, while estimating the service capabilities in the multi-agent simulation. The Adjusted/Enhanced Multi-Agent Estimation technique suggests using basic activity plans from the activity-based model in the multi-agent simulation, and then using an upgraded version of the multi-agent simulation to estimate novel mode usage and service capabilities. We advice forecasters to implement one of these two methodologies to estimate novel mode usage to ensure their predictions are as useful as possible for their region. We also advice forecasters to use all path, person, and location type variables when calculating the mode choice utility. Doing so will ensure the most realistic modeling environment. We beleive our results relating to ride hail ridership, ride hail wait times, ride hail ridership, and mode choice structure analysis provide sufficient evidence to back these claims.

Overall, accurately predicting the behavior and service capabilities of new transport technologies is the key to a clean and improved future. New transport technologies are central to clean air, organized cities, and the effective movement of people. By accurately predicting the usage of new transport technologies, we can help improve our cities and our lives. We can also be better prepared economically and mentally for the change that new technology brings. Overall, we can directly change the course of our future by how we estimate novel mode behavior, and so, should we not estimate it with the best approaches available? This research along with the future research we suggest will help in the efforts to accurately predict the ever changing behavior and capabilities of transportation itself.  




